stages:
  preprocess_data:
    cmd: python src/preprocess_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/preprocess_data.py
    - data_given/adjustment_details.csv
    - data_given/item_movement.csv
    outs:
    - data/raw/adjustment_details.pkl
    - data/raw/item_movement.pkl
    # - data/processed/item_master_4_model.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data/raw/adjustment_details.pkl
    - data/raw/item_movement.pkl
    # - data/processed/item_master_4_model.csv
    outs:
    - data/processed/train.csv
    - data/processed/test.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - src/train_and_evaluate.py
    - data/processed/train.csv
    - data/processed/test.csv
    params:
    - estimators.XGBoost.params.n_estimators
    - estimators.XGBoost.params.learning_rate
    - estimators.XGBoost.params.max_depth
    - estimators.XGBoost.params.gamma
    metrics:
    - report/scores.json:
        cache: false
    outs: 
    - saved_models/model.joblib
